services:
  geojupyter:
    build: "."
    command: uv run jupyter lab --allow-root --no-browser --ip=0.0.0.0 --ServerApp.token="jupytercon2025"
    volumes:
      - "${CONTENT_DIR}:/app/content"
    ports:
      - "8888:8888"
    restart: "unless-stopped"
